# Makefile generated by MakefileGenerator.cs
# *DO NOT EDIT*

UNREALROOTPATH = /home/pipopolam/UE5
GAMEPROJECTFILE =/home/pipopolam/Documents/Unreal Projects/MasteryOfWar/MasteryOfWar.uproject

TARGETS = \
	MasteryOfWar-Linux-DebugGame  \
	MasteryOfWar-Linux-Shipping  \
	MasteryOfWar \
	MasteryOfWarEditor-Linux-DebugGame  \
	MasteryOfWarEditor-Linux-Shipping  \
	MasteryOfWarEditor \
	UnrealEditor-Linux-DebugGame  \
	UnrealEditor-Linux-Shipping  \
	UnrealEditor \
	UnrealGame-Linux-DebugGame  \
	UnrealGame-Linux-Shipping  \
	UnrealGame\
	configure

BUILD = bash "$(UNREALROOTPATH)/Engine/Build/BatchFiles/Linux/Build.sh"
PROJECTBUILD = "$(UNREALROOTPATH)/Engine/Binaries/ThirdParty/DotNet/6.0.302/linux/dotnet" "$(UNREALROOTPATH)/Engine/Binaries/DotNET/UnrealBuildTool/UnrealBuildTool.dll"

all: StandardSet

RequiredTools: CrashReportClient-Linux-Shipping CrashReportClientEditor-Linux-Shipping ShaderCompileWorker UnrealLightmass EpicWebHelper-Linux-Shipping

StandardSet: RequiredTools UnrealFrontend MasteryOfWarEditor UnrealInsights

DebugSet: RequiredTools UnrealFrontend-Linux-Debug MasteryOfWarEditor-Linux-Debug


MasteryOfWar-Linux-DebugGame:
	 $(PROJECTBUILD) MasteryOfWar Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

MasteryOfWar-Linux-Shipping:
	 $(PROJECTBUILD) MasteryOfWar Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

MasteryOfWar:
	 $(PROJECTBUILD) MasteryOfWar Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

MasteryOfWarEditor-Linux-DebugGame:
	 $(PROJECTBUILD) MasteryOfWarEditor Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

MasteryOfWarEditor-Linux-Shipping:
	 $(PROJECTBUILD) MasteryOfWarEditor Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

MasteryOfWarEditor:
	 $(PROJECTBUILD) MasteryOfWarEditor Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealEditor-Linux-DebugGame:
	 $(BUILD) UnrealEditor Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealEditor-Linux-Shipping:
	 $(BUILD) UnrealEditor Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealEditor:
	 $(BUILD) UnrealEditor Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealGame-Linux-DebugGame:
	 $(BUILD) UnrealGame Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealGame-Linux-Shipping:
	 $(BUILD) UnrealGame Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealGame:
	 $(BUILD) UnrealGame Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

configure:
	xbuild /property:Configuration=Development /verbosity:quiet /nologo "$(UNREALROOTPATH)/Engine/Source/Programs/UnrealBuildTool/UnrealBuildTool.csproj"
	$(PROJECTBUILD) -projectfiles -project="\"$(GAMEPROJECTFILE)\"" -game -engine 

.PHONY: $(TARGETS)
